---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
  labels:
    storage: wp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/wordpress
