---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress
spec:
  selector:
    matchLabels:
      storage: wp
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
