---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb
  labels:
    storage: mariadb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard #без поля не связывалось по умолчаю пустое значение
  hostPath:
    path: /mnt/data/mariadb
