---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb
spec:
  selector:
    matchLabels:
      storage: mariadb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
